openapi: "3.0.0"

info:
  version: 1.0.0
  title: Stocktrade
  description: Stocktrade backend API specification

servers:
  - url: http://localhost:3000/api/user

paths:
  /signup:
    post:
      summary: Signs up a new user
      tags:
        - account
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                firstName:
                  type: string
                lastName:
                  type: string
                middleName:
                  type: string
                mobileNumber:
                  type: string
                password:
                  type: string
                gender:
                  type: string
                dob:
                  type: string
              required: 
                - email
                - middleName
                - firstName
                - mobileNumber 
                - password
                - lastName
                - gender
                - dob
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: Registration successfull
                  status:
                    type: boolean
                  data:
                    type: object
                    properties:
                      firstName: 
                        type: string
                      mobileNumber:
                        type: string
                      email:
                        type: string
                        format: email
                      token:
                        type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
               oneOf:
                - type: object
                  properties:
                    message:
                      type: string
                      default: user is already registered
                    status:
                      type: boolean
                      default: false
                    data:
                      type: object                 
